-- 1. Table: seguimientos
-- Creates a one-to-many relationship with observaciones for strict tracking.

CREATE TABLE IF NOT EXISTS seguimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observacion_id BIGINT REFERENCES observaciones(id) ON DELETE CASCADE,
    
    fecha_respuesta DATE,          -- Fecha de respuesta de la entidad
    campo_detallar TEXT,           -- Campo para detallar
    fecha_plan_accion DATE,        -- Fecha plan de acción
    respuesta TEXT,                -- Respuesta
    fecha_seguimiento DATE,        -- Fecha del seguimiento
    analisis TEXT,                 -- Análisis respectivo
    nro_informe TEXT,              -- Nuevo: Número de informe del seguimiento
    
    creado_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Migración para tabla existente
ALTER TABLE seguimientos ADD COLUMN IF NOT EXISTS nro_informe TEXT;
